create table if not exists public.ats_board_registry (
  id bigint generated by default as identity primary key,
  provider text not null,
  company text not null,
  board_key text not null,
  careers_url text,
  geo_scope text not null default 'india_remote',
  priority integer not null default 50,
  active boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (provider, board_key)
);

create index if not exists ats_board_registry_active_priority_idx
  on public.ats_board_registry (active, priority desc);

create index if not exists ats_board_registry_provider_idx
  on public.ats_board_registry (provider);

alter table if exists public.job_alerts
  add column if not exists source_quality_tier text,
  add column if not exists ats_provider text,
  add column if not exists ats_board_key text,
  add column if not exists source_urls jsonb default '[]'::jsonb;

create index if not exists job_alerts_source_quality_tier_idx
  on public.job_alerts (source_quality_tier);

create index if not exists job_alerts_ats_provider_idx
  on public.job_alerts (ats_provider);

create index if not exists job_alerts_ats_board_key_idx
  on public.job_alerts (ats_board_key);
